### ISSUE TITLE
newline macro for latex export

### ISSUE THREAD

**Issue by bruceravel** [fniessen/org-macros#2]
Hi,
This and orgmk make my life easier, so thanks!

I suggest this change to the newline macro:
```
#+MACRO: newline @@latex:\hspace{0pt}\\@@ @@html:<br>@@
```
i.e. add the zero-width space before the double backslash.  Without the zws, you have to be  mindful of where you use the `{{{newline}}}` macro.  If the `\\` ends up at the beginning of a line, latex will complain about there not being a line to terminate.  This is obviated by inserting the zero width space and doing so should have no impact on other uses of the macro.

**Comment by fniessen** [comment]
Thanks for your suggestion!
